# Generated by Django 2.0.2 on 2018-06-28 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
